// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPY0PKNGqAGiCmqn09TCDRxMjYwR-xbLQ',
    appId: '1:739451127143:web:e03257992f4c09f96a5bc2',
    messagingSenderId: '739451127143',
    projectId: 'find-85195',
    authDomain: 'find-85195.firebaseapp.com',
    storageBucket: 'find-85195.appspot.com',
    measurementId: 'G-QYHWEQJWV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrli8BytovT4vfh33pFfHvVPSyNRT1NEc',
    appId: '1:739451127143:android:7ba0d221f00258de6a5bc2',
    messagingSenderId: '739451127143',
    projectId: 'find-85195',
    storageBucket: 'find-85195.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7VBfkyf52PpjDAn7Ycav8HoNT1sDVcBM',
    appId: '1:739451127143:ios:900395f273a6fe9f6a5bc2',
    messagingSenderId: '739451127143',
    projectId: 'find-85195',
    storageBucket: 'find-85195.appspot.com',
    iosBundleId: 'com.example.find',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7VBfkyf52PpjDAn7Ycav8HoNT1sDVcBM',
    appId: '1:739451127143:ios:f9cc020aae39f73f6a5bc2',
    messagingSenderId: '739451127143',
    projectId: 'find-85195',
    storageBucket: 'find-85195.appspot.com',
    iosBundleId: 'com.example.find.RunnerTests',
  );
}
